
/**
 * Auto-generated harness for Sleuth fuzzing
 * Bug ID: 2
 * Bug Type: StatusError
 * Affected Parameters: WPNAV_SPEED, WPNAV_ACCEL, MOT_SPOOL_TIME
 * Generated by: adg_to_sleuth.py
 *
 * This harness wraps the vulnerable function extracted from ArduPilot
 * to enable Sleuth-based deep impact analysis.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include <unistd.h>
#include <fcntl.h>

/* ============================================================
 * Simulation of ArduPilot types needed by the vulnerable code
 * ============================================================ */

typedef float AP_Float;
typedef int16_t AP_Int16;
typedef uint16_t AP_UInt16;
typedef int32_t AP_Int32;
typedef uint32_t AP_UInt32;
typedef uint8_t AP_Int8;

/* Parameter container - simplified from AP_Param */
typedef struct {
    AP_Float value;
    AP_Float default_val;
    AP_Float min_val;
    AP_Float max_val;
} ParamFloat;

typedef struct {
    AP_Int32 value;
    AP_Int32 default_val;
    AP_Int32 min_val;
    AP_Int32 max_val;
} ParamInt32;

/* ============================================================
 * Parameter Definitions - generated from bug input
 * ============================================================ */
static ParamInt32 param_0 = { .value = 500, .default_val = 500, .min_val = 250, .max_val = 1000 };
static ParamInt32 param_1 = { .value = 100, .default_val = 100, .min_val = 50, .max_val = 200 };
static ParamFloat param_2 = { .value = 0.5f, .default_val = 0.5f, .min_val = 0.2f, .max_val = 1.0f };

/* ============================================================
 * Forward declarations of vulnerable functions
 * (These should be extracted from ArduPilot source)
 * ============================================================ */
/* TODO: Extract and include actual ArduPilot function declarations */
/* Affected module: AP_Motors */
/* Affected module: AC_WPNav */


/* ============================================================
 * Input reading - reads binary fuzz input and sets parameters
 * ============================================================ */
static int read_input(const char *filename) {
    unsigned char buf[4096];
    int fd = open(filename, O_RDONLY);
    if (fd < 0) {
        perror("open");
        return -1;
    }

    ssize_t n = read(fd, buf, sizeof(buf));
    if (n < 0) {
        perror("read");
        close(fd);
        return -1;
    }
    close(fd);

    if (n < 12) {
        fprintf(stderr, "Input too small: %zd bytes (need at least 12)\\n", n);
        return -1;
    }

    /* Parse input and set parameters */
    size_t offset = 0;
    memcpy(&param_0.value, buf + offset, sizeof(AP_Int32));
    offset += sizeof(AP_Int32);
    fprintf(stderr, "[WPNAV_SPEED] = %d\n", param_0.value);
    memcpy(&param_1.value, buf + offset, sizeof(AP_Int32));
    offset += sizeof(AP_Int32);
    fprintf(stderr, "[WPNAV_ACCEL] = %d\n", param_1.value);
    memcpy(&param_2.value, buf + offset, sizeof(AP_Float));
    offset += sizeof(AP_Float);
    fprintf(stderr, "[MOT_SPOOL_TIME] = %f\n", param_2.value);

    return 0;
}

/* ============================================================
 * Main - AFL/Sleuth entry point
 * ============================================================ */
int main(int argc, char **argv) {
    const char *input_file = NULL;

    if (argc > 1) {
        input_file = argv[1];
    } else {
        /* When run by AFL/Sleuth, input is passed as argument or via stdin */
        input_file = getenv("AFL_FILE");
        if (!input_file) {
            input_file = "/dev/stdin";
        }
    }

    if (read_input(input_file) < 0) {
        return 1;
    }

    /* ============================================================
     * Trigger the vulnerable code path
     * ============================================================ */
    /* TODO: Call the vulnerable function(s) with the parsed parameters */
    /* Example pattern:
     *   1. Initialize the subsystem with parameters
     *   2. Call the function that caused the crash
     *   3. The crash should be reproduced here
     */
    fprintf(stderr, "Setting WPNAV_SPEED = %d/%f\n", param_0.value, (float)param_0.value);
    fprintf(stderr, "Setting WPNAV_ACCEL = %d/%f\n", param_1.value, (float)param_1.value);
    fprintf(stderr, "Setting MOT_SPOOL_TIME = %d/%f\n", param_2.value, (float)param_2.value);

    /* === VULNERABLE CODE PATH === */
    /* TODO: Insert the actual vulnerable function call */
    /* abort() is a placeholder - replace with actual code */
    // abort();


    return 0;
}
